-- $keymaps:text
vim.keymap.set('n', 'w1', 'mL')
vim.keymap.set('n', 'w2', 'mN')
vim.keymap.set('n', 'w3', 'mM')
vim.keymap.set('n', 'w4', 'mO')
vim.keymap.set('n', 'e1', '\'L')
vim.keymap.set('n', 'e2', '\'N')
vim.keymap.set('n', 'e3', '\'M')
vim.keymap.set('n', 'e4', '\'O')
vim.keymap.set('n', '<S-End>', 'o<Esc>')
vim.keymap.set('n', '<S-Home>', 'ddk')
vim.keymap.set('n', '<C-S-Left>', '<<')
vim.keymap.set('n', '<C-S-Right>', '>>')
vim.keymap.set('v', '<C-S-Left>', '<gv')
vim.keymap.set('v', '<C-S-Right>', '>gv')
vim.keymap.set('v', '<S-Left>', 'ygv<Esc>')
vim.keymap.set('n', '<S-Left>', 'yy')
vim.keymap.set({'n', 'v'}, '<S-Right>', 'p')
vim.keymap.set('i', '<S-Right>', '<esc>pa')
vim.keymap.set('n', '<M-CR>', 'md*ggn')
vim.keymap.set('n', '<M-]>', '\'d')
vim.keymap.set('v', '<C-S-Down>', ':m \'>+1<CR>gv=gv')
vim.keymap.set('v', '<C-S-Up>', ':m \'<-2<CR>gv=gv')
vim.keymap.set({ 'n', 'v' }, '<Space>', '<Nop>', { silent = true })
vim.keymap.set('v', 'z', '<esc>')
vim.keymap.set('v', '<S-Up>', '<Up>')
vim.keymap.set('v', '<S-Down>', '<Down>')
vim.keymap.set('n', '<S-Down>', '<S-v>j')
vim.keymap.set('n', '<S-Up>', '<S-v>k')
vim.keymap.set('v', '<leader>a', ':s/\\d\\+/\\=(submatch(0)+1)/g')
vim.keymap.set('n', '<leader>cw', ':%s/\\<<C-r><C-w>\\>/')
vim.keymap.set('n', 'cw', 'ciw')
vim.keymap.set('n', 'dw', 'diw')
vim.keymap.set('n', 'vw', 'viw')
vim.keymap.set({'v', 'x'}, '<leader>p', '\"_dP')
vim.keymap.set('n', '<leader>f', 'zf%')
vim.keymap.set('n', '<C-End>', 'k<S-v>jj<S-j>')
vim.keymap.set('v', '<M-End>', 'J')
vim.keymap.set('n', '<C-z>', 'u')
vim.keymap.set('n', '<C-M-z>', ':UndotreeToggle<CR>')
vim.keymap.set('n', '<M-z>', '<C-r>')
vim.keymap.set('n', 'daa', 'F,dt)')
vim.keymap.set('n', '<C-space>', 'yy<C-del>p')
vim.keymap.set('n', '<C-\\>', 'yy\\\\p')
vim.keymap.set({'n', 'i', 'v'}, '<C-s>', function () vim.cmd('silent write') end)
vim.keymap.set('n', '<C-x>', 'dd')

-- $keymaps:insert
vim.keymap.set('i', '<C-Space>', ' ')
vim.keymap.set('i', '<C-Delete>', '<BS><Delete>')
-- vim.keymap.set('i', '<C-x>', '<C-n>')
vim.keymap.set('i', '<M-a>', '<C-o>$;')
vim.keymap.set('i', '<C-z>', '<Esc>[s1z=A')
vim.keymap.set('n', 'x', 'i')
vim.keymap.set('n', 'X', 'I')
vim.keymap.set('i', '<M-e>', 'X<bs><C-o>:E<CR>')
vim.keymap.set('i', '<M-r>', 'X<bs><C-o>:R<CR>')
vim.keymap.set('i', '<M-g>', 'X<bs><C-o>:D<CR>')
vim.keymap.set('i', '<M-j>', 'X<bs><C-o>:J<CR>')
vim.keymap.set('i', '<C-m>', '$$<Left>')

-- $keymaps:terminal
vim.keymap.set('t', '<C-q>', '<C-\\><C-n>')

-- $keymaps:navigation
vim.keymap.set('n', '<Up>', 'gk')
vim.keymap.set('n', '<Down>', 'gj')
-- vim.keymap.set('i', '<Up>', '<C-o>gk')
-- vim.keymap.set('i', '<Down>', '<C-o>gj')
vim.keymap.set({'n', 'v'}, '<M-Up>', '5k')
vim.keymap.set('v', '<S-M-Up>', '5k')
vim.keymap.set({'n', 'v'}, '<M-Down>', '5j')
vim.keymap.set('v', '<S-M-Down>', '5j')
vim.keymap.set({'n', 'v'}, '<M-Left>', '5h')
vim.keymap.set({'n', 'v'}, '<M-Right>', '5l')
vim.keymap.set('i', '<M-up>', '<C-o>5k')
vim.keymap.set('i', '<M-down>', '<C-o>5j')
vim.keymap.set('i', '<M-left>', '<C-o>5h')
vim.keymap.set('i', '<M-right>', '<C-o>5l')
vim.keymap.set({'n', 'v'}, '<M-a>', '%')
vim.keymap.set('n', 'n', 'nzz')
vim.keymap.set('n', 'N', 'Nzz')
vim.keymap.set('n', '<C-M-Left>', '<C-^>')
vim.keymap.set('t', '<C-M-Left>', '<C-\\><C-n><C-^>')
vim.keymap.set('n', '<C-M-Right>', 'gf')

-- $keymaps:window
vim.keymap.set('n', '<C-Left>', '<C-w>h')
vim.keymap.set('n', '<C-Down>', '<C-w>j')
vim.keymap.set('n', '<C-Up>', '<C-w>k')
vim.keymap.set('n', '<C-Right>', '<C-w>l')
vim.keymap.set('n', '<C-w><Left>', '<C-w>H')
vim.keymap.set('n', '<C-w><Right>', '<C-w>L')
vim.keymap.set('n', '<C-w><Up>', '<C-w>K')
vim.keymap.set('n', '<C-w><Down>', '<C-w>J')
vim.keymap.set('n', '<C-M-o>', '<C-w>+')
vim.keymap.set('n', '<C-M-l>', '<C-w>-')
vim.keymap.set('n', '<C-M-i>', '<C-w>>')
vim.keymap.set('n', '<C-M-u>', '<C-w><')
vim.keymap.set('n', '<C-M-k>', '<C-w>=')
vim.keymap.set('n', '<C-M-w>', '<C-w>o')
vim.keymap.set('n', '<C-Delete>', '<cmd>wqa<CR>')
vim.keymap.set('n', '<C-c>', function()
    if (#vim.api.nvim_list_wins() < 2) then
        for _, ui in pairs(vim.api.nvim_list_uis()) do
            if ui.chan and not ui.stdout_tty then
                vim.fn.chanclose(ui.chan)
            end
        end
    else
        local buf = vim.api.nvim_win_get_buf(0)
        if vim.bo[buf].readonly or (vim.api.nvim_buf_is_loaded(buf) and vim.api.nvim_buf_get_name(buf) == '') then
            vim.cmd('quit!')
        else
            vim.cmd('wqa')
        end
    end
end, { noremap = true })

-- $keymaps:command
vim.keymap.set('n', '<M-t>', function () vim.cmd('silent !$TERMINAL --title \'Terminal\' -e zsh -c \'nvim-server\' &') end)
vim.keymap.set('n', '<M-b>', function () vim.cmd('silent !$TERMINAL --title \'Viewer\' -e zsh -c \'nvim-server; br\'&') end)
vim.keymap.set('n', '<leader>ek', function () vim.cmd('edit $NIXOS_CONFIG/home-manager/home.nix') end)
vim.keymap.set('n', '<leader>eK', function () vim.cmd('tabnew $NIXOS_CONFIG/home-manager/home.nix') end)
vim.keymap.set('n', '<leader>el', function () vim.cmd('edit $NIXOS_CONFIG/home-manager/src/nvim/init.lua') end)
vim.keymap.set('n', '<leader>eL', function () vim.cmd('tabnew $NIXOS_CONFIG/home-manager/src/nvim/init.lua') end)
vim.keymap.set('n', '<leader>en', function () vim.cmd('edit $NIXOS_LOCAL/home-local.nix') end)
vim.keymap.set('n', '<leader>eN', function () vim.cmd('tabnew $NIXOS_LOCAL/system-local.nix') end)
vim.keymap.set('n', '<leader>ee', function ()
    local ft = vim.bo.filetype
    vim.cmd('sp $NIXOS_CONFIG/home-manager/src/nvim/UltiSnips/' .. ft .. '.snippets')
end)
vim.keymap.set('n', '<leader>cd', function () vim.cmd('Copilot disable') end)
vim.keymap.set('n', '<leader>ce', function () vim.cmd('Copilot enable') end)
vim.keymap.set('n', 'Z', function () vim.cmd('ToggleBool') end)
vim.keymap.set('n', '<M-s>', function () vim.cmd('silent Gitsigns preview_hunk_inline') end)
