return {
    "folke/trouble.nvim",
    opts = {
        icons = {
            indent = {
                top           = "│ ",
                middle        = "├╴",
                last          = "└╴",
                fold_open     = " +",
                fold_closed   = "- ",
                ws            = " ",
                file          = "",
            },
            folder_closed   = "",
            folder_open     = "",
            kinds = {
                Array         = "A ",
                Boolean       = "B ",
                Class         = "",
                Constant      = "",
                Constructor   = "C ",
                Enum          = "E ",
                EnumMember    = "",
                Event         = "",
                Field         = "",
                File          = "",
                Function      = "F ",
                Interface     = "I ",
                Key           = "K ",
                Method        = "",
                Module        = "M ",
                Namespace     = "N ",
                Null          = "",
                Number        = "",
                Object        = "",
                Operator      = "O ",
                Package       = "P ",
                Property      = "",
                String        = "S ",
                Struct        = "",
                TypeParameter = "TP ",
                Variable      = "V ",
            },
        },
    },
    -- cmd = "Trouble",
    keys = {
        {
            "<C-M-d>",
            "<cmd>Trouble diagnostics toggle<cr>",
            desc = "Diagnostics (Trouble)",
        },
    },
    lazy = false,
}
