hkust: -p 1
alipay-hk: -k medium
octopus, bochk: -k anshort
paypal: -k medium
phone, bochk-atm-pin, signal, alipay-hk-payment-password: -k mediumpin
induction-and-enrichment-activities: -k longpin
archlinux-ramak, debian-ramak, nixos-ramak, windows-ramak, archlinux-root, debian-root, nixos-root: -k mediumpin
bochk-payment-passcode: -k mediumpin
europa: -k long
arxiv: -k anlong
amy-test: -c [("qwertyui",3),("ZXCVBNMK",3),("32415",2)]
