hkust: -p 1
alipay-hk: -k medium
induction-and-enrichment-activities: -k longpin
octopus, bochk: -k anshort
paypal: -k medium
phone, bochk-atm-pin, signal, alipay-hk-payment-password: -k mediumpin
archlinux-ramak, debian-ramak, nixos-ramak, windows-ramak, archlinux-root, debian-root, nixos-root: -k mediumpin
bochk-passcode: -k mediumpin
europa: -k long
arxiv: -k anlong
