vim.loader.enable()
local km = vim.keymap

km.set('n', 'w1', 'mL')
km.set('n', 'w2', 'mN')
km.set('n', 'w3', 'mM')
km.set('n', 'w4', 'mO')
km.set('n', 'e1', '\'L')
km.set('n', 'e2', '\'N')
km.set('n', 'e3', '\'M')
km.set('n', 'e4', '\'O')
km.set('n', '<S-End>', 'o<Esc>')
km.set('n', '<S-Home>', 'ddk')
km.set('n', '<C-S-Left>', '<<')
km.set('n', '<C-S-Right>', '>>')
km.set('v', '<C-S-Left>', '<gv')
km.set('v', '<C-S-Right>', '>gv')
km.set('v', '<S-Left>', 'ygv<Esc>')
km.set('n', '<S-Left>', 'yy')
km.set({'n', 'v'}, '<S-Right>', 'p')
km.set('i', '<S-Right>', '<esc>pa')
km.set('n', '<M-CR>', 'md*ggn')
km.set('n', '<M-]>', '\'d')
km.set('v', '<C-S-Down>', ':m \'>+1<CR>gv=gv')
km.set('v', '<C-S-Up>', ':m \'<-2<CR>gv=gv')
km.set({ 'n', 'v' }, '<Space>', '<Nop>', { silent = true })
km.set('v', 'z', '<esc>')
km.set('v', '<S-Up>', '<Up>')
km.set('v', '<S-Down>', '<Down>')
km.set('n', '<S-Down>', '<S-v>j')
km.set('n', '<S-Up>', '<S-v>k')
km.set('v', '<leader>a', ':s/\\d\\+/\\=(submatch(0)+1)/g')
km.set('n', '<leader>cw', ':%s/\\<<C-r><C-w>\\>/')
km.set('n', 'cw', 'ciw')
km.set('n', 'dw', 'diw')
km.set('n', 'vw', 'viw')
km.set({'v', 'x'}, '<leader>p', '\"_dP')
km.set('n', '<leader>f', 'zf%')
km.set('n', '<C-End>', 'k<S-v>jj<S-j>')
km.set('v', '<M-End>', 'J')
km.set('n', '<C-z>', 'u')
km.set('n', '<C-M-z>', ':UndotreeToggle<CR>')
km.set('n', '<M-z>', '<C-r>')
km.set('n', 'daa', 'F,dt)')
km.set('n', '<C-space>', 'yy<C-del>p')

-- $keymaps:insert
km.set('i', '<C-Space>', ' ')
km.set('i', '<C-Delete>', '<BS><Delete>')
-- km.set('i', '<C-x>', '<C-n>')
km.set('i', '<M-a>', '<C-o>$;')
km.set('i', '<C-z>', '<Esc>[s1z=A')
km.set('n', 'x', 'i')
km.set('n', 'X', 'I')
km.set('i', '<M-e>', 'X<bs><C-o>:E<CR>')
km.set('i', '<M-r>', 'X<bs><C-o>:R<CR>')
km.set('i', '<M-g>', 'X<bs><C-o>:D<CR>')
km.set('i', '<M-j>', 'X<bs><C-o>:J<CR>')
km.set('i', '<C-m>', '$$<Left>')

-- $keymaps:terminal
km.set('t', '<C-q>', '<C-\\><C-n>')

-- $keymaps:navigation
km.set('n', '<Up>', 'gk')
km.set('n', '<Down>', 'gj')
-- km.set('i', '<Up>', '<C-o>gk')
-- km.set('i', '<Down>', '<C-o>gj')
km.set({'n', 'v'}, '<M-Up>', '5k')
km.set('v', '<S-M-Up>', '5k')
km.set({'n', 'v'}, '<M-Down>', '5j')
km.set('v', '<S-M-Down>', '5j')
km.set({'n', 'v'}, '<M-Left>', '5h')
km.set({'n', 'v'}, '<M-Right>', '5l')
km.set('i', '<M-up>', '<C-o>5k')
km.set('i', '<M-down>', '<C-o>5j')
km.set('i', '<M-left>', '<C-o>5h')
km.set('i', '<M-right>', '<C-o>5l')
km.set({'n', 'v'}, '<M-a>', '%')
km.set('n', 'n', 'nzz')
km.set('n', 'N', 'Nzz')
km.set('n', '<C-M-Left>', '<C-^>')
km.set('t', '<C-M-Left>', '<C-\\><C-n><C-^>')
km.set('n', '<C-M-Right>', 'gf')

-- $keymaps:window
km.set('n', '<C-Left>', '<C-w>h')
km.set('n', '<C-Down>', '<C-w>j')
km.set('n', '<C-Up>', '<C-w>k')
km.set('n', '<C-Right>', '<C-w>l')
km.set('n', '<C-w><Left>', '<C-w>H')
km.set('n', '<C-w><Right>', '<C-w>L')
km.set('n', '<C-w><Up>', '<C-w>K')
km.set('n', '<C-w><Down>', '<C-w>J')
km.set('n', '<C-M-o>', '<C-w>+')
km.set('n', '<C-M-l>', '<C-w>-')
km.set('n', '<C-M-i>', '<C-w>>')
km.set('n', '<C-M-u>', '<C-w><')
km.set('n', '<C-M-k>', '<C-w>=')
km.set('n', '<C-M-w>', '<C-w>o')
km.set('n', '<C-Delete>', '<cmd>wqa<CR>')
km.set('n', '<C-c>', '<cmd>wq<CR>')

-- $keymaps:command
-- km.set('n', '<C-a>', function () vim.cmd('silent !$TERMINAL --title \'Terminal\' &') end)
-- km.set('n', '<C-M-x>', function () vim.cmd('silent !$TERMINAL --title \'Viewer\' -e zsh -c \'nvim-server; br\'&') end)
-- km.set('n', '<leader>k', function () vim.cmd('edit $NIXOS_CONFIG/home-manager/main.nix') end)
-- km.set('n', '<leader>K', function () vim.cmd('tabnew $NIXOS_CONFIG/home-manager/main.nix') end)
-- km.set('n', '<leader>l', function () vim.cmd('edit $NIXOS_CONFIG/dotfiles/nvim/init.lua') end)
-- km.set('n', '<leader>L', function () vim.cmd('tabnew $NIXOS_CONFIG/dotfiles/nvim/init.lua') end)
-- km.set('n', '<leader>n', function () vim.cmd('edit $NIXOS_LOCAL/home-local.nix') end)
-- km.set('n', '<leader>N', function () vim.cmd('edit $NIXOS_LOCAL/system-local.nix') end)
-- km.set('n', '<leader>ee', function ()
--     local ft = vim.bo.filetype
--     vim.cmd('sp $NIXOS_CONFIG/dotfiles/nvim/UltiSnips/' .. ft .. '.snippets')
-- end)
-- km.set('n', '<leader>cd', function () vim.cmd('Copilot disable') end)
-- km.set('n', '<leader>ce', function () vim.cmd('Copilot enable') end)
-- km.set('n', 'Z', function () vim.cmd('ToggleBool') end)
-- km.set('n', '<M-s>', function () vim.cmd('silent Gitsigns preview_hunk_inline') end)
