-- $text keymaps
km.set('v', '<S-Left>', 'ygv<Esc>')
km.set('n', '<S-Left>', 'yy')
km.set('v', '<C-S-Left>', '\"+y')
km.set('n', '<C-S-Left>', '\"+yy')
km.set({'n', 'v'}, '<S-Right>', 'p')
km.set({'n', 'v'}, '<C-S-Right>', '\"+p')
km.set('v', '<C-S-Down>', ":m '>+1<CR>gv=gv")
km.set('v', '<C-S-Up>', ":m '<-2<CR>gv=gv")
km.set({ 'n', 'v' }, '<Space>', '<Nop>', { silent = true })
km.set('v', 'z', '<esc>')
km.set('v', '<S-Up>', '<Up>')
km.set('v', '<S-Down>', '<Down>')
km.set('n', '<S-Down>', '<S-v>j')
km.set('n', '<S-Up>', '<S-v>k')
km.set('v', '<leader>a', ':s/\\d\\+/\\=(submatch(0)+1)/g')
km.set('n', '<leader>cw', ":%s/\\<<C-r><C-w>\\>/")
km.set('n', 'cw', 'ciw')
km.set('n', 'dw', 'diw')
km.set('x', '<leader>p', '\"_dP')
km.set('n', '<leader>f', 'zf%')
km.set('n', '<C-End>', 'k<S-v>jj<S-j>')

-- $insert keymaps
km.set('n', 'x', 'i')
km.set('i', '<M-z>', '<C-n>')
km.set('i', '<C-z>', '<C-o>:R<CR>')
km.set('i', '<C-x>', '<C-o>:E<CR>')
km.set('i', '<M-s>', '<C-o>$;')
km.set('i', '<C-q>', '<Esc>[s1z=A')
km.set('i', '<C-w>', function () vim.cmd('silent write') end)

-- $navigation keymaps
-- km.set('n', '<Up>', "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })
-- km.set('n', '<Down>', "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
km.set('n', '<Up>', 'gk')
km.set('n', '<Down>', 'gj')
km.set('i', '<Up>', '<C-o>gk')
km.set('i', '<Down>', '<C-o>gj')
km.set({'n', 'v'}, '<M-Up>', '10k')
km.set({'n', 'v'}, '<M-Down>', '10j')
km.set({'n', 'v'}, '<M-Left>', 'b')
km.set({'n', 'v'}, '<M-Right>', 'w')
km.set('i', '<M-up>', '<C-o>10k')
km.set('i', '<M-down>', '<C-o>10j')
km.set('i', '<M-left>', '<C-o>b')
km.set('i', '<M-right>', '<C-o>w')
km.set({'n', 'v'}, '<M-a>', '%')
km.set('n', 'n', 'nzz')
km.set('n', 'N', 'Nzz')   
km.set('n', '<C-M-left>', '<C-^>')
km.set('n', '<C-M-right>', 'gf')

-- $window keymaps
km.set('n', '<C-left>', '<C-w>h')
km.set('n', '<C-Down>', '<C-w>j')
km.set('n', '<C-Up>', '<C-w>k')
km.set('n', '<C-right>', '<C-w>l')
-- km.set('i', '<C-Left>', '<C-o><C-w>h')
-- km.set('i', '<C-Down>', '<C-o><C-w>j')
-- km.set('i', '<C-Up>', '<C-o><C-w>k')
-- km.set('i', '<C-Right>', '<C-o><C-w>l')
km.set('n', '<C-w><Left>', '<C-w>H')
km.set('n', '<C-w><Right>', '<C-w>L')
km.set('n', '<C-w><Up>', '<C-w>K')
km.set('n', '<C-w><Down>', '<C-w>J')
km.set('n', '<C-M-o>', '<C-w>+')
km.set('n', '<C-M-l>', '<C-w>-')
km.set('n', '<C-M-i>', '<C-w>>')
km.set('n', '<C-M-u>', '<C-w><')
km.set('n', '<C-M-k>', '<C-w>=')

-- $command keymaps
km.set('n', 'Z', function () vim.cmd('quit') end)
km.set('n', '<leader>tr', function () vim.cmd('silent !alacritty -e ranger&') end)
km.set('n', '<C-a>', function () vim.cmd('silent !alacritty&') end)
km.set('n', '<leader>l', function () vim.cmd('tabnew $NIXOS_CONFIG/home.nix') end)
km.set('n', '<leader>k', function () vim.cmd('edit $NIXOS_CONFIG/home.nix') end)
km.set('n', '<leader>L', function () vim.cmd('tabnew $NIXOS_CONFIG/dotfiles/nvim/init.lua') end)
km.set('n', '<leader>K', function () vim.cmd('edit $NIXOS_CONFIG/dotfiles/nvim/init.lua') end)
km.set('n', '<leader>o', ':Compile<CR>')
km.set('n', '<leader>x', function () vim.cmd('CompileSilent') end)
km.set({'n','i'}, '<C-s>', function () vim.cmd('CompileSilent') end)
km.set('n', '<leader>vp', function () vim.cmd('ViewPdf') end)
km.set('n', '<leader>ee', function () vim.cmd('UltiSnipsEdit') end)
km.set('n', 'd[', vim.diagnostic.goto_prev, { desc = 'Go to previous diagnostic message' })
km.set('n', 'd]', vim.diagnostic.goto_next, { desc = 'Go to next diagnostic message' })
km.set('n', '<leader>de', vim.diagnostic.open_float, { desc = 'Open floating diagnostic message' })
km.set('n', '<leader>dq', vim.diagnostic.setloclist, { desc = 'Open diagnostics list' })

-- $telescope keymaps
km.set('n', '<C-x>', require('telescope.builtin').buffers, { desc = '[ ] Find existing buffers' })
km.set('n', '<C-_>', function()
	require('telescope.builtin').current_buffer_fuzzy_find(require('telescope.themes').get_dropdown {
		previewer = false,
		theme = 'ivy',
	})
end)
km.set('n', '<M-/>', require('telescope.builtin').live_grep)
km.set('n', '<leader>cd', require('telescope.builtin').builtin)
km.set('n', '<leader>:', require('telescope.builtin').commands)
km.set('n', '<M-S-Right>', require('telescope').extensions.neoclip['a'])
km.set('n', '<C-x>', function () require('telescope').extensions.file_browser.file_browser({ path = vim.loop.cwd() }) end)
km.set('n', '<C-f>', require('telescope.builtin').find_files)
km.set('n', '<C-d>', require('telescope.builtin').oldfiles)
km.set('n', '<M-CR>', require('telescope.builtin').help_tags)
km.set('n', '<leader>s', require('telescope.builtin').grep_string)
km.set('n', '<leader>q', require('telescope.builtin').quickfix)
km.set('n', '<leader>cs', require('telescope.builtin').colorscheme)
km.set('n', '<C-j>', require('telescope.builtin').jumplist)
km.set('n', '<C-z>', 'u')
